blank_issues_enabled: false
contact_links:
  - name: JetBrains Plugin Marketplace
    url: https://plugins.jetbrains.com/plugin/23376-openintools
    about: Check out the plugin page for downloads and reviews
  - name: Documentation
    url: https://github.com/abd3lraouf/OpenInToolsSupport/blob/main/README.md
    about: Read the documentation to learn more about the plugin 