blank_issues_enabled: false
contact_links:
  - name: JetBrains Marketplace
    url: https://plugins.jetbrains.com/plugin/MARKETPLACE_ID
    about: Visit the plugin page on JetBrains Marketplace
  - name: Email Support
    url: mailto:support@example.com
    about: Contact us directly for urgent issues 